# Generated by Django 3.0.6 on 2020-05-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crowdednessRating', models.IntegerField()),
                ('levelNumber', models.IntegerField()),
                ('locationName', models.CharField(max_length=100)),
                ('closingTime', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='levels',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
