# Generated by Django 3.0.6 on 2020-05-16 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sgw', '0002_auto_20200516_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyspot',
            name='openingTime',
            field=models.IntegerField(0),
            preserve_default=False,
        ),
    ]
