# Generated by Django 3.0.6 on 2020-05-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgw', '0006_auto_20200519_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyspot',
            name='closingTime',
            field=models.TimeField(default='20:00'),
        ),
        migrations.AddField(
            model_name='studyspot',
            name='openingTime',
            field=models.TimeField(default='20:00'),
        ),
    ]
