# Generated by Django 3.0.6 on 2020-05-19 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgw', '0007_auto_20200519_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.CharField(max_length=100)),
                ('openingTime', models.TimeField(default='20:00')),
                ('closingTime', models.TimeField(default='20:00')),
            ],
        ),
        migrations.RemoveField(
            model_name='studyspot',
            name='closingTime',
        ),
        migrations.RemoveField(
            model_name='studyspot',
            name='crowdednessRating',
        ),
        migrations.RemoveField(
            model_name='studyspot',
            name='openingTime',
        ),
        migrations.AlterField(
            model_name='studyspot',
            name='locationName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgw.Location'),
        ),
    ]
