# Generated by Django 3.0.6 on 2020-05-24 15:30

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sgw', '0008_auto_20200519_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='geom',
            field=djgeojson.fields.PointField(default=[1, 1]),
            preserve_default=False,
        ),
    ]
