# Generated by Django 3.0.6 on 2020-06-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgw', '0009_location_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(
                default='location/placeholder.jpg', upload_to='location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyspot',
            name='image',
            field=models.ImageField(
                default='studyspot/placeholder.jpg', upload_to='studyspot'),
            preserve_default=False,
        ),
    ]
