# Generated by Django 3.0.6 on 2020-06-24 15:08

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sgw', '0010_auto_20200623_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySpotContrib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('openingTime', models.TimeField(default='20:00')),
                ('closingTime', models.TimeField(default='20:00')),
                ('image', models.ImageField(upload_to='studyspot')),
                ('geom', djgeojson.fields.PointField()),
                ('studyspotname', models.CharField(max_length=100)),
                ('levelNumber', models.IntegerField()),
                ('airConditioned', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, null=True)),
                ('discussionFriendly', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, null=True)),
                ('wallSockets', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, null=True)),
            ],
        ),
    ]
