# Generated by Django 3.0.6 on 2020-08-13 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sgw', '0012_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyspot',
            name='users_favorited',
            field=models.ManyToManyField(related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
